import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react"; 
import { Nav } from "./component";
import { Poppins } from 'next/font/google';
import Footer from "./sections/Footer"
const poppins = Poppins({
  weight: ['400', '700'], // Specify the font weights you want to use
  subsets: ['latin'],      // Specify subsets you need, like 'latin'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the type for children
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) 
 {
  return (
    <html lang="en">
       <body className={poppins.className}>
        <Nav />
        {children}
        <section className="bg-[#F4E1C6]"><Footer /></section>
      </body>
    </html>
  );
}
